require 'rainbow'
require 'rainbow/refinement'

using Rainbow
puts "red".red
puts "yellow".yellow
puts "blue".blue
puts "magenta".magenta
puts "cyan".cyan
puts "white".white

puts Rainbow("aliceblue").aliceblue
puts Rainbow("antiquewhite").antiquewhite
puts Rainbow("aqua").aqua
puts Rainbow("aquamarine").aquamarine
puts Rainbow("azure").azure
puts Rainbow("beige").beige
puts Rainbow("bisque").bisque
puts Rainbow("blanchedalmond").blanchedalmond
puts Rainbow("blueviolet").blueviolet
puts Rainbow("brown").brown
puts Rainbow("burlywood").burlywood
puts Rainbow("cadetblue").cadetblue
puts Rainbow("chartreuse").chartreuse
puts Rainbow("chocolate").chocolate
puts Rainbow("coral").coral
puts Rainbow("cornflower").cornflower
puts Rainbow("cornsilk").cornsilk
puts Rainbow("crimson").crimson
puts Rainbow("darkblue").darkblue
puts Rainbow("darkcyan").darkcyan
puts Rainbow("darkgoldenrod").darkgoldenrod
puts Rainbow("darkgray").darkgray
puts Rainbow("darkgreen").darkgreen
puts Rainbow("darkkhaki").darkkhaki
puts Rainbow("darkmagenta").darkmagenta
puts Rainbow("darkolivegreen").darkolivegreen
puts Rainbow("darkorange").darkorange
puts Rainbow("darkorchid").darkorchid
puts Rainbow("darkred").darkred
puts Rainbow("darksalmon").darksalmon
puts Rainbow("darkseagreen").darkseagreen
puts Rainbow("darkslateblue").darkslateblue
puts Rainbow("darkslategray").darkslategray
puts Rainbow("darkturquoise").darkturquoise
puts Rainbow("darkviolet").darkviolet
puts Rainbow("deeppink").deeppink
puts Rainbow("deepskyblue").deepskyblue
puts Rainbow("dimgray").dimgray
puts Rainbow("dodgerblue").dodgerblue
puts Rainbow("firebrick").firebrick
puts Rainbow("floralwhite").floralwhite
puts Rainbow("forestgreen").forestgreen
puts Rainbow("fuchsia").fuchsia
puts Rainbow("gainsboro").gainsboro
puts Rainbow("ghostwhite").ghostwhite
puts Rainbow("gold").gold
puts Rainbow("goldenrod").goldenrod
puts Rainbow("gray").gray
puts Rainbow("greenyellow").greenyellow
puts Rainbow("honeydew").honeydew
puts Rainbow("hotpink").hotpink
puts Rainbow("indianred").indianred
puts Rainbow("indigo").indigo
puts Rainbow("ivory").ivory
puts Rainbow("khaki").khaki
puts Rainbow("lavender").lavender
puts Rainbow("lavenderblush").lavenderblush
puts Rainbow("lawngreen").lawngreen
puts Rainbow("lemonchiffon").lemonchiffon
puts Rainbow("lightblue").lightblue
puts Rainbow("lightcoral").lightcoral
puts Rainbow("lightcyan").lightcyan
puts Rainbow("lightgoldenrod").lightgoldenrod
puts Rainbow("lightgray").lightgray
puts Rainbow("lightgreen").lightgreen
puts Rainbow("lightpink").lightpink
puts Rainbow("lightsalmon").lightsalmon
puts Rainbow("lightseagreen").lightseagreen
puts Rainbow("lightskyblue").lightskyblue
puts Rainbow("lightslategray").lightslategray
puts Rainbow("lightsteelblue").lightsteelblue
puts Rainbow("lightyellow").lightyellow
puts Rainbow("lime").lime
puts Rainbow("limegreen").limegreen
puts Rainbow("linen").linen
puts Rainbow("maroon").maroon
puts Rainbow("mediumaquamarine").mediumaquamarine
puts Rainbow("mediumblue").mediumblue
puts Rainbow("mediumorchid").mediumorchid
puts Rainbow("mediumpurple").mediumpurple
puts Rainbow("mediumseagreen").mediumseagreen
puts Rainbow("mediumslateblue").mediumslateblue
puts Rainbow("mediumspringgreen").mediumspringgreen
puts Rainbow("mediumturquoise").mediumturquoise
puts Rainbow("mediumvioletred").mediumvioletred
puts Rainbow("midnightblue").midnightblue
puts Rainbow("mintcream").mintcream
puts Rainbow("mistyrose").mistyrose
puts Rainbow("moccasin").moccasin
puts Rainbow("navajowhite").navajowhite
puts Rainbow("navyblue").navyblue
puts Rainbow("oldlace").oldlace
puts Rainbow("olive").olive
puts Rainbow("olivedrab").olivedrab
puts Rainbow("orange").orange
puts Rainbow("orangered").orangered
puts Rainbow("orchid").orchid
puts Rainbow("palegoldenrod").palegoldenrod
puts Rainbow("palegreen").palegreen
puts Rainbow("paleturquoise").paleturquoise
puts Rainbow("palevioletred").palevioletred
puts Rainbow("papayawhip").papayawhip
puts Rainbow("peachpuff").peachpuff
puts Rainbow("peru").peru
puts Rainbow("pink").pink
puts Rainbow("plum").plum
puts Rainbow("powderblue").powderblue
puts Rainbow("purple").purple
puts Rainbow("rebeccapurple").rebeccapurple
puts Rainbow("rosybrown").rosybrown
puts Rainbow("royalblue").royalblue
puts Rainbow("saddlebrown").saddlebrown
puts Rainbow("salmon").salmon
puts Rainbow("sandybrown").sandybrown
puts Rainbow("seagreen").seagreen
puts Rainbow("seashell").seashell
puts Rainbow("sienna").sienna
puts Rainbow("silver").silver
puts Rainbow("skyblue").skyblue
puts Rainbow("slateblue").slateblue
puts Rainbow("slategray").slategray
puts Rainbow("snow").snow
puts Rainbow("springgreen").springgreen
puts Rainbow("steelblue").steelblue
puts Rainbow("tan").tan
puts Rainbow("teal").teal
puts Rainbow("thistle").thistle
puts Rainbow("tomato").tomato
puts Rainbow("turquoise").turquoise
puts Rainbow("violet").violet
puts Rainbow("webgray").webgray
puts Rainbow("webgreen").webgreen
puts Rainbow("webmaroon").webmaroon
puts Rainbow("webpurple").webpurple
puts Rainbow("wheat").wheat
puts Rainbow("whitesmoke").whitesmoke
puts Rainbow("yellowgreen").yellowgreen
